-- Quiz questions for the 41 new modules (cocktail recipes + wine + whiskey + beer + spirits + sales).
-- 2 questions per module = 82 new questions.

with quizzes(title, position, question, opts, correct, expl) as (
  values

  -- ── COCKTAIL RECIPES ───────────────────────────────────────────────────
  ('Margarita', 0, 'What type of tequila is best for a classic Margarita?', '["Añejo","Reposado","100% agave blanco","Mixto"]'::jsonb, 2, 'Blanco (100% agave) is the classic Margarita spirit. Its clean agave flavor shines with lime and Cointreau.'),
  ('Margarita', 1, 'Why do bartenders prefer Cointreau over cheap triple sec?', '["Higher ABV","Less sweet, more orange oil, cleaner flavor","Cheaper per pour","Better color"]'::jsonb, 1, 'Cointreau is drier with genuine orange-peel oil. Cheap triple sec is mostly sugar syrup with artificial flavor.'),

  ('Espresso Martini', 0, 'Why must you shake an Espresso Martini hard?', '["To chill the vodka","To create the signature foam from espresso oils","To dilute the coffee","To dissolve the sugar"]'::jsonb, 1, 'Espresso has natural oils that emulsify when shaken vigorously, creating the thick foam top that defines the drink.'),
  ('Espresso Martini', 1, 'What''s the difference between Mr Black and Kahlúa?', '["Mr Black is sweeter","Mr Black is drier and more coffee-forward; Kahlúa is sweeter with vanilla","They''re identical","Kahlúa is coffee-free"]'::jsonb, 1, 'Mr Black emphasizes bitter coffee; Kahlúa emphasizes vanilla sweetness. Craft bars prefer Mr Black; mainstream drinkers often prefer Kahlúa.'),

  ('Moscow Mule', 0, 'What''s the key difference between ginger beer and ginger ale?', '["Ginger beer is brewed with real ginger and is spicier; ginger ale is carbonated water with flavoring","They''re the same","Ginger ale is stronger","Ginger beer has no ginger"]'::jsonb, 0, 'Ginger beer is brewed (often with real ginger), bold and spicy. Ginger ale is mild carbonated water with ginger flavoring. Mules need ginger beer.'),
  ('Moscow Mule', 1, 'Why are Moscow Mules traditionally served in copper mugs?', '["Looks better on Instagram","Copper conducts cold, keeping the drink colder longer","Legal requirement","Taste is different in copper"]'::jsonb, 1, 'Copper is an excellent thermal conductor — the mug gets ice-cold to the touch and keeps the drink chilled longer than glass.'),

  ('Mojito', 0, 'What''s the biggest mistake people make when muddling mint for a Mojito?', '["Not enough mint","Crushing too hard — releases bitter chlorophyll from shredded leaves","Using dried mint","Adding mint last"]'::jsonb, 1, 'Gentle pressing releases aromatic oils. Over-muddling shreds the leaves and extracts bitter green chlorophyll, ruining the drink.'),
  ('Mojito', 1, 'What type of ice is traditional in a Mojito?', '["Large cubes","No ice","Crushed ice","Ice spheres"]'::jsonb, 2, 'Crushed ice is traditional — it chills quickly, dilutes appropriately, and creates the slushy texture that makes a Mojito refreshing.'),

  ('Daiquiri', 0, 'A classic Daiquiri is shaken and strained into a coupe. True or false: it contains pineapple juice.', '["True — pineapple is essential","False — only rum, lime, and simple syrup","True — pineapple and coconut","False — it uses grapefruit instead"]'::jsonb, 1, 'A classic Daiquiri is just rum + lime + simple syrup. No pineapple, no coconut, no blender. The frozen version is a different drink.'),
  ('Daiquiri', 1, 'Why does rum quality matter MORE in a Daiquiri than in a Margarita?', '["Daiquiris use more rum","The rum is front and center with minimal other flavors to hide behind","Rum is always expensive","Margaritas don''t use spirits"]'::jsonb, 1, 'A Daiquiri is just rum + lime + sugar. The rum has nowhere to hide. In a Margarita, Cointreau and lime can mask a mediocre tequila.'),

  ('Manhattan', 0, 'What''s the traditional base spirit for a Manhattan?', '["Bourbon","Vodka","Rye whiskey","Scotch"]'::jsonb, 2, 'Rye is the classic Manhattan spirit — its spice and dryness balance the sweet vermouth. Bourbon makes a softer version (also good, but not traditional).'),
  ('Manhattan', 1, 'Why should you always refrigerate sweet vermouth after opening?', '["It tastes better cold","It''s wine-based and oxidizes within weeks if left at room temp","Legal requirement","It prevents bacterial growth"]'::jsonb, 1, 'Sweet vermouth is fortified wine. Once opened, it oxidizes like any wine. Refrigerated, it lasts 4-6 weeks. Room temp, it goes stale in days.'),

  ('Cosmopolitan', 0, 'What type of cranberry juice should you use in a Cosmo?', '["Cranberry juice cocktail","100% unsweetened cranberry juice","Cranberry-apple blend","Any brand works the same"]'::jsonb, 1, '100% unsweetened cranberry juice is tart and makes a balanced, properly pink drink. The "cocktail" version is mostly sugar water and makes it too sweet and too red.'),
  ('Cosmopolitan', 1, 'A properly made Cosmopolitan should be what color?', '["Bright red","Dark purple","Pink","Clear"]'::jsonb, 2, 'A Cosmo should be PINK, not red. If it''s dark red, there''s too much cranberry juice. The cranberry is an accent, not the star.'),

  ('French 75', 0, 'What tops a French 75?', '["Tonic water","Club soda","Champagne or sparkling wine","Ginger beer"]'::jsonb, 2, 'A French 75 is gin + lemon + sugar, shaken and strained into a flute, then topped with champagne or sparkling wine.'),
  ('French 75', 1, 'You don''t need expensive Champagne for a French 75. What''s a good budget substitute?', '["Beer","Cava or Crémant ($12-25)","Flat white wine","Tonic water"]'::jsonb, 1, 'Cava ($12-15) or Crémant ($18-25) work perfectly in a French 75 — save the $50 Champagne for sipping.'),

  ('Mai Tai', 0, 'What ingredient gives a Mai Tai its distinctive nutty, creamy flavor?', '["Pineapple juice","Coconut milk","Orgeat (almond syrup)","Falernum"]'::jsonb, 2, 'Orgeat is an almond-based syrup that provides the creamy, nutty backbone of a real Mai Tai. Without it, you just have a rum sour.'),
  ('Mai Tai', 1, 'Does a classic Mai Tai contain pineapple juice or orange juice?', '["Yes — both","Only pineapple","Only orange","Neither — the original has no fruit juice besides lime"]'::jsonb, 3, 'Trader Vic''s original Mai Tai contains only lime juice (plus rum, curaçao, orgeat). No pineapple, no OJ. Those are resort-pool additions.'),

  ('Paloma', 0, 'What''s the main mixer in a Paloma?', '["Orange juice","Lime soda","Grapefruit soda","Cola"]'::jsonb, 2, 'The Paloma is tequila + grapefruit soda (Jarritos Toronja, Squirt, or Ting) + lime + salt. It''s Mexico''s most popular tequila drink.'),
  ('Paloma', 1, 'What''s the simplest cousin of the Paloma, popular in Texas?', '["Margarita","Ranch Water (tequila + Topo Chico + lime)","Michelada","Tequila Sunrise"]'::jsonb, 1, 'Ranch Water is tequila + Topo Chico (sparkling mineral water) + lime. That''s it. The ultimate low-effort Texas highball.'),

  ('Piña Colada', 0, 'What''s the difference between coconut cream and coconut milk for a Piña Colada?', '["No difference","Coconut cream (Coco López) is thick and sweetened; coconut milk is thin and unsweetened","Coconut milk is thicker","Coconut cream is unsweetened"]'::jsonb, 1, 'Coco López is sweetened coconut cream — thick, rich, sweet. Coconut milk is thin and unsweetened. Piña Coladas need the cream version.'),
  ('Piña Colada', 1, 'What''s a "Dirty Piña Colada"?', '["Made with coconut water","Made with aged dark rum instead of white","Made without ice","Made with vodka"]'::jsonb, 1, 'A Dirty Piña Colada uses aged rum (Appleton, El Dorado) instead of white, adding toasted caramel depth to the tropical coconut-pineapple base.'),

  ('Negroni', 0, 'The classic Negroni ratio is:', '["2:1:1","3:1:1","1:1:1 (equal parts)","1:2:1"]'::jsonb, 2, 'The Negroni is equal parts gin, Campari, and sweet vermouth — 1:1:1. No room to hide; every ingredient must be good.'),
  ('Negroni', 1, 'What''s a Negroni Sbagliato?', '["Negroni with mezcal","Negroni with prosecco instead of gin","Negroni without Campari","Frozen Negroni"]'::jsonb, 1, '"Sbagliato" means "mistaken" — legend says a bartender accidentally grabbed prosecco instead of gin. The result: lighter, bubbly, brunch-friendly.'),

  ('Aperol Spritz', 0, 'What''s the standard Aperol Spritz ratio?', '["1:1:1","3 Prosecco : 2 Aperol : 1 soda","Equal parts Aperol and soda","All Prosecco with a splash of Aperol"]'::jsonb, 1, 'The official ratio is 3-2-1: 3 parts Prosecco, 2 parts Aperol, 1 part soda. Served over ice in a large wine glass with an orange slice.'),
  ('Aperol Spritz', 1, 'How does Aperol differ from Campari?', '["Aperol is much more bitter","Aperol is milder, sweeter, lower ABV (11%); Campari is much more bitter at 24% ABV","They''re the same product","Campari is orange, Aperol is red"]'::jsonb, 1, 'Aperol is lighter, sweeter, and 11% ABV — much more approachable. Campari is intensely bitter at 24% ABV. Different drinks, different audiences.'),

  ('Whiskey Sour', 0, 'Adding egg white to a Whiskey Sour creates what effect?', '["Makes it stronger","Creates a silky foam top and creamy texture","Adds egg flavor","Thickens the drink like a milkshake"]'::jsonb, 1, 'Egg white emulsifies when shaken, creating a velvety foam. It adds texture, not flavor — the lemon acid neutralizes any egg taste.'),
  ('Whiskey Sour', 1, 'What''s the vegan substitute for egg white in cocktails?', '["Heavy cream","Aquafaba (chickpea water)","Milk","Coconut cream"]'::jsonb, 1, 'Aquafaba — the liquid from canned chickpeas — foams exactly like egg white when shaken. Same visual, same texture, fully vegan.'),

  ('Tom Collins', 0, 'A Tom Collins is basically a gin sour lengthened with what?', '["Tonic water","Club soda","Ginger beer","Champagne"]'::jsonb, 1, 'A Tom Collins = gin + lemon + sugar + club soda. If you swap the soda for champagne, it becomes a French 75.'),
  ('Tom Collins', 1, 'What glass is literally named after this cocktail?', '["Highball glass","Rocks glass","Collins glass","Coupe"]'::jsonb, 2, 'The tall, narrow Collins glass is named after the Tom Collins. It''s designed to hold the longer drink with ice and soda.'),

  -- ── WINE EXPANDED ──────────────────────────────────────────────────────
  ('Australian Chardonnay', 0, 'Which Australian region makes cool-climate, Burgundy-style Chardonnay?', '["Barossa Valley","Hunter Valley","Yarra Valley","McLaren Vale"]'::jsonb, 2, 'Yarra Valley (Victoria) produces tight, mineral, elegant Chardonnay — the opposite of the warm, oaky stereotype. Think white Burgundy with a Southern Hemisphere accent.'),
  ('Australian Chardonnay', 1, 'Shaw + Smith M3 Chardonnay is from which cool-climate region?', '["Barossa","Adelaide Hills","Hunter Valley","Margaret River"]'::jsonb, 1, 'Adelaide Hills is a cool-climate region that produces refined, restrained Chardonnay. Shaw + Smith M3 (~$30) is one of its best.'),

  ('New Zealand Sauvignon Blanc', 0, 'Which NZ region produces 90% of the country''s Sauvignon Blanc?', '["Hawke''s Bay","Central Otago","Martinborough","Marlborough"]'::jsonb, 3, 'Marlborough on the South Island dominates NZ Sauvignon Blanc — explosive passionfruit, grapefruit, and cut-grass character.'),
  ('New Zealand Sauvignon Blanc', 1, 'Cloudy Bay is famous for being the NZ Sauv Blanc that started the global craze. When was it founded?', '["1965","1975","1985","1995"]'::jsonb, 2, 'Cloudy Bay''s first vintage was 1985. It introduced the world to the distinctive Marlborough Sauvignon Blanc style.'),

  ('South African Wine', 0, 'What is South Africa''s most planted white grape?', '["Chardonnay","Sauvignon Blanc","Chenin Blanc","Riesling"]'::jsonb, 2, 'Chenin Blanc (called "Steen" locally) is South Africa''s signature white. Ranges from bone-dry to lusciously sweet. Exceptional value.'),
  ('South African Wine', 1, 'Pinotage is a cross between which two grapes?', '["Cabernet Sauvignon + Merlot","Pinot Noir + Cinsaut","Syrah + Grenache","Tempranillo + Garnacha"]'::jsonb, 1, 'Pinotage was created in South Africa in 1925 by crossing Pinot Noir and Cinsaut. It''s unique to South Africa.'),

  ('California Reds Deep-Dive', 0, 'Which California region is known as the heartland of Zinfandel?', '["Napa Valley","Sonoma Coast","Dry Creek Valley and Lodi","Santa Barbara"]'::jsonb, 2, 'Dry Creek Valley (Sonoma) and Lodi (Central Valley) are the two premier Zinfandel regions in California. Ridge, Turley, and Seghesio are icons.'),
  ('California Reds Deep-Dive', 1, 'Tablas Creek is a pioneer of what wine style in Paso Robles?', '["Napa Cabernet","Burgundy Pinot","Rhône-style blends (GSM)","German Riesling"]'::jsonb, 2, 'Tablas Creek brought Rhône varieties (Grenache, Syrah, Mourvèdre, Roussanne) to Paso Robles from Château de Beaucastel. They pioneered the Central Coast Rhône movement.'),

  ('California Whites Deep-Dive', 0, 'Which aromatic grape is gaining popularity in Paso Robles and Lodi?', '["Chardonnay","Riesling","Viognier","Pinot Grigio"]'::jsonb, 2, 'Viognier — aromatic, with honeysuckle, apricot, and peach — thrives in Paso Robles, Lodi, and Central Coast. Dry but not sweet.'),
  ('California Whites Deep-Dive', 1, 'Albariño, the Spanish coastal grape, is now grown in California. What food does it pair with best?', '["Steak","Chocolate","Seafood","Pizza"]'::jsonb, 2, 'Albariño is crisp, saline, and citrusy — the perfect seafood wine. In California, Tangent and Bokisch lead the way.'),

  ('Oregon Whites', 0, 'What is Oregon''s most-planted white grape?', '["Chardonnay","Riesling","Sauvignon Blanc","Pinot Gris"]'::jsonb, 3, 'Pinot Gris is Oregon''s #1 white grape. Richer than Italian Pinot Grigio, with pear, apple, and a honeyed texture.'),
  ('Oregon Whites', 1, 'Oregon Chardonnay is most similar in style to which famous region?', '["Napa Valley","Burgundy","Chablis only","Argentina"]'::jsonb, 1, 'Oregon Chardonnay is lean, mineral, and Burgundian — closer to white Burgundy than to buttery California Chard.'),

  ('Italian Reds — Chianti to Amarone', 0, 'Amarone della Valpolicella is made using what special technique?', '["Carbonic maceration","Appassimento — drying grapes before pressing","Cold fermentation","Blending with brandy"]'::jsonb, 1, 'Grapes are dried (appassimento) for 3-4 months before pressing, concentrating sugars and flavors. This creates Amarone''s massive, rich, 15%+ ABV character.'),
  ('Italian Reds — Chianti to Amarone', 1, 'What grape makes Chianti?', '["Nebbiolo","Corvina","Sangiovese","Barbera"]'::jsonb, 2, 'Chianti is Sangiovese-based (with possible blending). It''s Tuscany''s signature grape — cherry, leather, bright acid, made for tomato-based food.'),

  ('Italian Whites — Pinot Grigio to Vermentino', 0, 'Alto Adige Pinot Grigio differs from Veneto Pinot Grigio how?', '["It''s sweeter","More structure, acidity, and minerality","It''s red","It''s sparkling"]'::jsonb, 1, 'Alto Adige (northern Italy, Alpine) produces more structured, acid-driven Pinot Grigio. Veneto versions tend to be lighter and more neutral.'),
  ('Italian Whites — Pinot Grigio to Vermentino', 1, 'Vermentino is the signature coastal white of which Italian region?', '["Tuscany","Puglia","Sardinia","Piedmont"]'::jsonb, 2, 'Sardinia (and Liguria) produce the best Vermentino — crisp, saline, citrus, almond. The ultimate Mediterranean seafood wine.'),

  ('How to Read a Wine Label', 0, 'Old World wine labels (France, Italy) typically feature what as the primary identifier?', '["The grape name","The region name","The vintage year","The winemaker''s photo"]'::jsonb, 1, 'Old World labels lead with REGION (Chablis, Barolo, Rioja). The grape is implied by the region. New World labels lead with the grape name.'),
  ('How to Read a Wine Label', 1, 'In the US, does "Reserve" on a wine label have a legal definition?', '["Yes — must be aged 3+ years","Yes — top 10% of production","No — it''s a marketing term with no legal meaning","Yes — must be estate-bottled"]'::jsonb, 2, 'In the US, "Reserve" has NO legal definition — any producer can use it. In Spain (Reserva) and Italy (Riserva), it has specific aging requirements.'),

  ('Wine Storage & Serving Temperature', 0, 'What happens to wine stored above 70°F for extended periods?', '["Nothing","It ages faster and degrades — cooked flavors, flat aromas","It gets stronger","It becomes sparkling"]'::jsonb, 1, 'Heat accelerates chemical reactions in wine, causing "cooked" or "maderized" flavors — stewed fruit, flat aromas, loss of freshness. 55°F is ideal storage.'),
  ('Wine Storage & Serving Temperature', 1, 'The 20-minute rule says:', '["Drink wine within 20 minutes of opening","Put reds in the fridge 20 min before serving; take whites out 20 min before","Only serve wine for 20 minutes","Store wine for 20 years"]'::jsonb, 1, 'Reds are often too warm and whites too cold at home. 20 minutes adjusts both to their ideal serving temperature.'),

  ('Wine for Beginners', 0, 'A customer says "I don''t know anything about wine." What''s the FIRST question to ask?', '["What''s your budget?","Red, white, or either?","Do you like tannins?","What region do you prefer?"]'::jsonb, 1, '"Red, white, or either?" immediately narrows the field by half and starts the conversation without intimidation. Budget and food come next.'),
  ('Wine for Beginners', 1, 'What price range is the quality/value sweet spot for wine beginners?', '["Under $8","$12-18","$25-35","Over $50"]'::jsonb, 1, '$12-18 is the inflection point where quality noticeably improves over sub-$10 bottles, without the complexity that would be wasted on a developing palate.'),

  ('Dessert Wines — Port, Sauternes & Ice Wine', 0, 'What''s the difference between Ruby Port and Tawny Port?', '["Ruby is aged in barrel, Tawny is not","Ruby is young and fruity; Tawny is barrel-aged with caramel and nut notes","They''re the same","Tawny is red, Ruby is brown"]'::jsonb, 1, 'Ruby is bottled young — vibrant, fruity. Tawny spends years in barrel, developing caramel, nuts, and dried-fruit character. 20-year Tawny is the sweet spot.'),
  ('Dessert Wines — Port, Sauternes & Ice Wine', 1, 'What cheese is the legendary pairing partner for Sauternes?', '["Cheddar","Mozzarella","Stilton (blue cheese)","Brie"]'::jsonb, 2, 'Sauternes + Stilton is one of wine''s greatest pairings — the honeyed sweetness of the wine against the salty, pungent blue cheese.'),

  -- ── WHISKEY EXPANDED ───────────────────────────────────────────────────
  ('Tennessee Whiskey', 0, 'What distinguishes Tennessee Whiskey from bourbon?', '["Different grains","The Lincoln County Process — charcoal mellowing before aging","Made only in Tennessee","Higher proof"]'::jsonb, 1, 'Tennessee Whiskey goes through the Lincoln County Process: filtering through sugar maple charcoal before barrel aging. This mellows the spirit and adds subtle sweetness.'),
  ('Tennessee Whiskey', 1, 'Uncle Nearest honors which historical figure?', '["Jack Daniel","Nathan Nearest Green, who taught Jack Daniel to distill","George Dickel","Jasper Newton"]'::jsonb, 1, 'Nathan "Nearest" Green was an enslaved man who is credited with teaching Jack Daniel the whiskey-making craft, including the charcoal mellowing process.'),

  ('Wheat Whiskey & Specialty Grains', 0, 'What''s the relationship between Weller and Pappy Van Winkle?', '["No connection","Same distillery, same mash bill — Weller is the younger/cheaper version","Made in different states","Different grain types"]'::jsonb, 1, 'Both Weller and Pappy Van Winkle are wheated bourbons from Buffalo Trace using the same mash bill. Weller is more available and much cheaper.'),
  ('Wheat Whiskey & Specialty Grains', 1, 'American Single Malt whiskey (Westland, Balcones) uses what primary grain?', '["Corn","Rye","Wheat","100% malted barley"]'::jsonb, 3, 'American Single Malt must be 100% malted barley, made at one distillery — same rules as Scotch single malt but made in America.'),

  ('Whiskey Blends & Budget Guide', 0, 'What bourbon under $25 is considered the best all-around value by most bartenders?', '["Maker''s Mark","Jack Daniel''s","Buffalo Trace","Crown Royal"]'::jsonb, 2, 'Buffalo Trace at ~$25 is the near-universal "best bourbon for the money." Approachable neat, excellent in cocktails, widely loved.'),
  ('Whiskey Blends & Budget Guide', 1, 'Monkey Shoulder is a blended Scotch from which region?', '["Islay","Highland","Speyside","Lowland"]'::jsonb, 2, 'Monkey Shoulder blends three Speyside single malts (Glenfiddich, Balvenie, Kininvie). Smooth, cocktail-friendly, under $30.'),

  ('Whiskey Cocktails at Home', 0, 'A customer buys rye whiskey. What cocktail ingredient should you upsell?', '["Tonic water","Sweet vermouth + Luxardo cherries (for Manhattans)","Orange juice","Ginger beer"]'::jsonb, 1, 'Rye + sweet vermouth + bitters + Luxardo cherry = Manhattan. The vermouth and cherries are the natural upsell with every rye purchase.'),
  ('Whiskey Cocktails at Home', 1, 'What makes an Irish Coffee different from just "whiskey in coffee"?', '["Nothing","A proper float of lightly-whipped heavy cream on top","It uses espresso","It''s served cold"]'::jsonb, 1, 'Irish Coffee has a specific technique: hot coffee + Irish whiskey + brown sugar, topped with a float of lightly-whipped cream that you drink the coffee through.'),

  -- ── BEER EXPANDED ──────────────────────────────────────────────────────
  ('Craft Beer for Beginners', 0, 'A customer says they only drink Bud Light. What''s the best one-step-up suggestion?', '["Imperial Stout","Triple IPA","A Helles Lager or Cream Ale","A barrel-aged sour"]'::jsonb, 2, 'Helles Lager or Cream Ale is one step up from Bud Light — still clean, crisp, and light but with more character. Don''t jump to the extreme end.'),
  ('Craft Beer for Beginners', 1, 'What format is best for a customer trying a new style for the first time?', '["A case of 24","A 6-pack","A single can or bottle","A keg"]'::jsonb, 2, 'Singles or mix-six packs are the discovery format. Don''t push a 6-pack of something untried. One can = low risk, high discovery.'),

  ('Beer & Food Pairing', 0, 'Hoppy beers (IPA) pair especially well with what type of food?', '["Delicate white fish","Spicy food (Indian, Mexican, Thai)","Chocolate desserts","Plain salads"]'::jsonb, 1, 'Hops cut through capsaicin (the heat compound in spicy food), making IPAs excellent with Indian curries, Mexican food, and Thai dishes.'),
  ('Beer & Food Pairing', 1, 'What''s the legendary pairing of Guinness with a specific seafood?', '["Salmon","Lobster","Oysters","Shrimp"]'::jsonb, 2, 'Guinness + oysters is a legendary pairing — the mineral/brine of the oysters complements the roasted malt of the stout. Both are from the sea and the earth.'),

  ('Non-Alcoholic Beer & Beverages', 0, 'Which NA beer brand is the current US market leader?', '["O''Doul''s","Heineken 0.0","Athletic Brewing","Budweiser Zero"]'::jsonb, 2, 'Athletic Brewing dominates the US NA beer market with genuinely excellent beers — Run Wild IPA, Free Wave Hazy, Upside Dawn Golden. Founded 2017.'),
  ('Non-Alcoholic Beer & Beverages', 1, 'What is Seedlip?', '["An NA beer","A distilled non-alcoholic spirit made with botanicals","A probiotic drink","An energy drink"]'::jsonb, 1, 'Seedlip is the pioneer of non-alcoholic spirits — distilled botanical waters that mimic gin/whiskey/vodka profiles. Used for premium mocktails.'),

  -- ── SPIRITS EXPANDED ───────────────────────────────────────────────────
  ('Non-Alcoholic Spirits', 0, 'What''s the best positioning for NA spirits in a store?', '["In a health food section","Near the cocktail mixers and premium spirits","Hidden in the back","In the beer cooler"]'::jsonb, 1, 'NA spirits should be near cocktail mixers and regular spirits — normalized, not segregated. Customers buying Fever-Tree tonic might also want Seedlip gin.'),
  ('Non-Alcoholic Spirits', 1, 'Lyre''s "Italian Orange" is designed to substitute for which spirit in cocktails?', '["Vodka","Campari","Aperol","Gin"]'::jsonb, 2, 'Lyre''s Italian Orange mimics Aperol — used for NA Aperol Spritzes, one of the most popular non-alcoholic cocktails.'),

  ('Ready-to-Drink (RTD) Guide', 0, 'What''s the #1 spirits-based RTD (ready-to-drink) in the US?', '["White Claw","Truly","High Noon (vodka + real juice + soda)","Four Loko"]'::jsonb, 2, 'High Noon is the leading spirits-based RTD — real vodka, real fruit juice, sparkling water. It outsells most hard seltzers in many markets.'),
  ('Ready-to-Drink (RTD) Guide', 1, 'Tip Top canned cocktails are considered bartender-quality. What''s their signature offering?', '["Hard seltzer","Old Fashioned, Negroni, Manhattan in a can","Vodka soda","Frozen margarita"]'::jsonb, 1, 'Tip Top makes actual cocktail-bar-quality Old Fashioneds, Negronis, and Manhattans in cans — real spirits, proper ratios, craft execution.'),

  ('Agave Beyond Tequila', 0, 'What gives mezcal its signature smoky flavor?', '["Chemical additives","The agave is pit-roasted underground before fermentation","Barrel aging","Smoked salt"]'::jsonb, 1, 'Mezcal agave is roasted in underground pits with hot rocks and wood — the smoke from this process infuses the agave before it''s fermented and distilled.'),
  ('Agave Beyond Tequila', 1, 'Sotol is technically not an agave spirit. What plant is it made from?', '["Blue agave","Corn","Dasylirion (desert spoon plant)","Sugarcane"]'::jsonb, 2, 'Sotol comes from the Dasylirion plant (not agave), native to northern Mexico''s Chihuahuan Desert. It''s herbal, grassy, and slightly minty.'),

  -- ── SALES & SERVICE ────────────────────────────────────────────────────
  ('Upselling Without Being Pushy', 0, 'What''s the most natural way to upsell?', '["Push the most expensive bottle","Bundle accessories with the base purchase","Criticize their first choice","Offer a discount"]'::jsonb, 1, 'Bundling ("that bourbon makes a great Old Fashioned — you''d just need bitters and cherries") adds items without pressuring a more expensive single bottle.'),
  ('Upselling Without Being Pushy', 1, 'When a customer says "is this for you or a gift?" and they say gift, what changes?', '["Nothing","They''re willing to spend more because they''re buying an impression, not just a drink","You should discount","They want the cheapest option"]'::jsonb, 1, 'Gift buyers purchase an impression. They''re open to nicer packaging, higher shelves, and premium bottles — they have implicit permission to spend.'),

  ('Reading the Customer', 0, 'A customer walks in and heads straight to a section, checking their phone. They are likely:', '["A Browser","A Mission Buyer","An Asker","An Enthusiast"]'::jsonb, 1, 'Beeline to a section + checking phone = they have a list and know what they want. Be helpful and fast, not chatty. "Can I help you find something?"'),
  ('Reading the Customer', 1, 'Which customer type represents your biggest selling opportunity?', '["The Browser","The Mission Buyer","The Asker","All equally"]'::jsonb, 2, 'The Asker wants guidance and is open to suggestions. They''re literally asking for your expertise — recommend freely, upsell naturally.'),

  ('Gift Recommendations by Budget', 0, 'What''s the fail-safe gift when you''re stuck?', '["Vodka","A $40-60 bottle of Champagne","A 6-pack of beer","Anything expensive"]'::jsonb, 1, 'Champagne is always appropriate — any adult, any occasion, any taste. A $40-60 bottle (Veuve, Taittinger, Perrier-Jouët) works every time.'),
  ('Gift Recommendations by Budget', 1, 'A $20 wine in a nice gift bag with tissue paper feels like a gift worth how much?', '["$20","$30-40","$10","$50+"]'::jsonb, 1, 'Presentation matters enormously in gifting. A wine bag with tissue paper costs the store $1-2 and adds $10-20 of perceived value.'),

  ('Holiday Season Playbook', 0, 'What is typically the single biggest sales week for a liquor store?', '["Super Bowl week","July 4th week","Thanksgiving week","Valentine''s week"]'::jsonb, 2, 'Thanksgiving week is the #1 revenue week for most liquor stores — wine for dinner, whiskey for gatherings, beer for football.'),
  ('Holiday Season Playbook', 1, 'During Dry January, the best strategy is:', '["Close the store","Stock NA beers and spirits prominently","Ignore it","Heavy discounts on alcohol"]'::jsonb, 1, 'Stock Athletic Brewing, Seedlip, Lyre''s, and other NA options prominently. Shelf talkers: "Going dry? Try these." Meet the customer where they are.'),

  ('Wine Club & Loyalty Programs', 0, 'What''s the simplest loyalty program a small liquor store can start?', '["A mobile app","A laminated punch card (buy 12, get 1 free)","Blockchain tokens","Annual membership fee"]'::jsonb, 1, 'A punch card costs nothing to create and drives repeat visits. No technology, no signup friction, instant reward. Start there.'),
  ('Wine Club & Loyalty Programs', 1, 'What do the best liquor store customers want most from a loyalty program?', '["Discounts","First access to allocated/limited bottles and personal recognition","Free delivery","Social media shoutouts"]'::jsonb, 1, 'Top customers value access (allocated bottles, early tastings) and recognition ("Hey Mike, we got that Barolo you liked") over discounts.'),

  ('Handling Difficult Customers', 0, 'You suspect a customer is intoxicated. What do you do?', '["Sell them a small bottle","Refuse the sale calmly and directly","Ignore it","Ask them to prove they''re sober"]'::jsonb, 1, 'Refuse clearly and without judgment: "I can''t sell alcohol to you right now. You''re welcome to come back another time." This protects you legally.'),
  ('Handling Difficult Customers', 1, 'A customer is angry. The first thing to do is:', '["Argue back","Call the police","Listen and let them vent for 30 seconds, then acknowledge","Ignore them"]'::jsonb, 2, 'Listen → Acknowledge ("I understand that''s frustrating") → Solve. Most anger de-escalates once the person feels heard.'),

  ('Merchandising & Shelf Placement', 0, 'Products at what height sell 30-40% more than bottom-shelf products?', '["Top shelf","Eye level (4-5 feet)","Knee level","Floor level"]'::jsonb, 1, 'Eye level = buy level. Products at 4-5 feet (average adult eye height) get the most visual attention and outsell identical products placed lower.'),
  ('Merchandising & Shelf Placement', 1, 'What is "cross-merchandising"?', '["Selling at a loss","Placing complementary items near each other (bitters near bourbon, limes near tequila)","International trade","Online + in-store sales"]'::jsonb, 1, 'Cross-merchandising places related items together: tonic near gin, Luxardo cherries near whiskey, salt + limes near tequila. Increases basket size.'),

  ('Inventory Basics for Staff', 0, 'What does FIFO stand for in inventory management?', '["First In, First Out","Fast Inventory, Fast Output","Final Inspection, Final Order","Frequently Inventoried, Frequently Ordered"]'::jsonb, 0, 'First In, First Out — older stock goes to the front, new stock goes behind. Prevents stale beer, dusty bottles, and expired products.'),
  ('Inventory Basics for Staff', 1, 'Industry average shrinkage (theft + breakage + errors) in liquor retail is approximately:', '["0.1%","2-3% of sales","10-15%","25%"]'::jsonb, 1, 'Shrinkage averages 2-3% of sales across the liquor retail industry. Regular cycle counts and visible security measures help control it.'),

  ('Legal: Age Verification & Compliance', 0, 'If a customer presents an expired ID, what should you do?', '["Accept it — the photo matches","Refuse the sale in most jurisdictions (expired ID is not valid)","Accept if expired less than a year","Call the police"]'::jsonb, 1, 'Expired IDs are technically invalid in most states. Politely refuse: "I need a valid, non-expired ID to sell alcohol. Store policy." Protect yourself.'),
  ('Legal: Age Verification & Compliance', 1, 'In an ABC sting operation, what happens?', '["Nothing — they just observe","An underage person with a real under-21 ID attempts a purchase; if you sell, you''re cited","They test your fire exits","They check food safety"]'::jsonb, 1, 'ABC agents send real minors with real vertical (under-21) IDs. If you don''t check or sell anyway: fines, license suspension, possible criminal charges.'),

  ('Store Safety & Loss Prevention', 0, 'What is the #1 shoplifting deterrent in a liquor store?', '["Cameras","Security guards","Greeting every customer with eye contact","Locking all bottles"]'::jsonb, 2, 'Greeting customers with eye contact ("Welcome!") is the single most effective deterrent. Thieves don''t want to be seen and remembered.'),
  ('Store Safety & Loss Prevention', 1, 'During a robbery, the correct response is:', '["Fight back","Chase the robber","Comply, give them what they want, call police after they leave","Lock the doors"]'::jsonb, 2, 'Comply. Money and inventory are replaceable. You are not. Give them what they want, then lock the door, call 911, and preserve the scene.')

)
insert into public.quiz_questions (module_id, position, question, options, correct_index, explanation)
select m.id, q.position, q.question, q.opts, q.correct, q.expl
from quizzes q
join public.modules m on m.is_seed = true and m.title = q.title
on conflict do nothing;
